### ISSUE TITLE
Jenkins build failure (isolated to a single PR) can be resolved only by adding the internal/socks dependency to glide.yaml

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#1070]
Jenkins build failure (isolated to [this single PR (PR-926)](https://github.com/edgexfoundry/edgex-go/pull/926)) can be resolved only by adding the internal/socks dependency to `glide.yaml` as follows:

```
- package: golang.org/x/net
  version: 92b859f39abd2d91a854c9f9c4621b2f5054a92d
  subpackages:
  - proxy
  - websocket
  - internal/socks
```
