### ISSUE TITLE
Maybe helpful for Guide 6.2.3.3. Add Device Service to docker-compose File

### ISSUE THREAD

**Issue by nbfhscl** [edgexfoundry/edgex-go#1291]
to enbale beginners quickly pass the guide documents, maybe some changes can be made.
- the deviceprofile "GS1-10P5.profile.yaml" dont work well directly for ModbusPal and docker-compose-delhi-0.7.1.
  in order to make it work, I changed some of the content to following
    ``` 
    name: RPM
        description: "RPM speed of the motor."
        attributes: 
            { primaryTable: "HOLDING_REGISTERS", startingAddress: "8455" }
        properties: 
            value:
                { type: "INT16", readWrite: "RW", minimum: "0", maximum: "1500", defaultValue: "1"}
            units:
                { type: "String", readWrite: "R", defaultValue: "rpm"}
   name: OutputVoltage
        description: "Output Voltage driving the motor."
        attributes: 
            { primaryTable: "HOLDING_REGISTERS", startingAddress: "8454" }
        properties: 
            value:
                { type: "INT16", readWrite: "RW", defaultValue: "1"}
            units:
                { type: "String", readWrite: "R", defaultValue: "Volts"}
    name: MotorControl
        get:
          - { index: "1", operation: "get", object: "RPM", parameter: "RPM", property: "value" }
          - { index: "2", operation: "get", object: "OutputVoltage", parameter: "OutputVoltage", property: "value" }
        set:
          - { operation: "set", resource: "RPM", parameter: "RPM" }
  ```
- The addressable given in the guide
  ```    
  { “name”: “Motor”, “method”: “GET”, “protocol”: “HTTP”, “address”: “10.0.1.29”, “port”: 502 }
  ```
  needs to be modified to following(Pay attention to the format of symbols)
  ```
  { "name": "Motor", "method": "GET", "protocol": "HTTP", "address": "172.17.0.1", "path": "1", "port": 502 }
  ```
- It will be much easier if you run ModbusPal.jar at the same localhost of docker. And the "Learn"   mode is really useful.
