### ISSUE TITLE
edgex-core-data doesn't start properly

### ISSUE THREAD

**Issue by giovannipersia** [edgexfoundry/edgex-go#1624]
### Description and Minimal Reproduction
Sometime (about 15% of time) on my Raspberry Pi the edgex-core-data microservice doesn't start properly

### Deployment Environment:
- Device: Raspberry Pi 3 B+
- OS: ubuntu-18.04.2-preinstalled-server-arm64+raspi3

### Docker Compose 
Attached the docker compose section (note: image has been rebuilt for ARM64 architecture):
```
data:
    image: mysubscription.dkr.ecr.us-east-1.amazonaws.com/edge-next/edgexfoundry/core-data-go-arm64:1.0.0
    ports:
      - "48080:48080"
      - "5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging
```

### Logs
These are container logs:
```
ubuntu@ubuntu:~$ sudo docker logs 39521ba2636c --follow
loader.go: fileName: /res/docker/configuration.toml
loader.go: Decode the configuration from TOML: &{false false true false false {* 5563 tcp zero} map[Logging:{edgex-support-logging 48061 http} Metadata:{edgex-core-metadata 48081 http}] map[Primary:{mongodb 5000 edgex-mongo 27017 core password coredata}] {true /edgex/logs/edgex-core-data.log } {edgex-core-consul 8500 consul} {30000 10s 15000 edgex-core-data 48080 http This is the Core Data Microservice 100 5000}}
```
