### ISSUE TITLE
Standardize RAML Headers

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1641]
While reviewing PR https://github.com/edgexfoundry/edgex-go/pull/1634 I found that RAML document headers are not consistent in all cases. They should look like this:

Example using core-command
```
title: core-comand
version: "1.1.x"
baseUri: "http://localhost:<SERVICE PORT>/api"
protocols: [ HTTP ]

documentation:
  - title: Welcome
    content: |
      Welcome to the <SERVICE NAME> API Documentation.
``` 
After which the `schemas` section follows and the rest of the content is laid out.

NOTE: Version has been changed to `1.1.x` to reflect Fuji release tag. Also `mediaType` is present in some docs and has been removed since there are endpoints which do not return `application/json`. This isn't shown in the published documentation anyway.
