### ISSUE TITLE
Faulty device profile.yaml throws metadata into limbo

### ISSUE THREAD

**Issue by OdysLam** [edgexfoundry/edgex-go#1695]
# 🐞 Bug Report

### Affected Services

Metadata 

### Is this a regression?

No idea

### Description and Minimal Reproduction

When uploading a faulty yaml device profile, the device profile is created but can not be deleted, used or modified. You can not upload a new profile with the same name (duplicate name) but you can neither delete it as it produced an error (when parsing the profile?).

The faulty profile:
```
# Copyright 2017 Dell Inc. All rights reserved.
name: "id459543-lora-device_service_profile2"
manufacturer: "Odysseas"
model: "1"
labels: 
    - "lora"
description: "generic lora device"
coreCommands: 
  - 
    name:  get_last_reading
    get: 
        path: "/api/v1/devices/{deviceId}/last_reading"
        responses:
          - 
            code: "200"
            description: "Last reading from lora device"
            expectedValues: ["lora-device-data"]
          -
            code: "503"
            description: "service unavailable"
            expectedValues: ["error_exists"]
  -
```

## 🌍  Your Environment
**Deployment Environment:**
Balena arm64 on raspberry pi 3 

**EdgeX Version:**

1.0.1

**Anything else relevant?**

**Comment by tsconn23** [comment]
> you can neither delete it as it produced an error (when parsing the profile?)

What is the error?

**Comment by OdysLam** [comment]
Just reproduced it:
When performing a GET request with deviceprofilename I get a `Item not found` and when I try to DELETE, I get a `Name cannot be blank`.

**Comment by tsconn23** [comment]
Cannot duplicate. `GET http://localhost:48081/api/v1/deviceprofile/name/id459543-lora-device_service_profile2` returns

<img width="810" alt="Screen Shot 2019-08-21 at 4 40 43 PM" src="https://user-images.githubusercontent.com/1342980/63470507-744b1f80-c432-11e9-8232-74bf30329db8.png">

`DELETE http://localhost:48081/api/v1/deviceprofile/name/id459543-lora-device_service_profile2` also works as expected

<img width="1070" alt="Screen Shot 2019-08-21 at 4 41 52 PM" src="https://user-images.githubusercontent.com/1342980/63470601-a5c3eb00-c432-11e9-945a-0955f67afd5c.png">

**Comment by tsconn23** [comment]
Re-attempting verification using Edinburgh v1.0.1 images. See running image list below.

```
~/Desktop $ docker ps
CONTAINER ID        IMAGE                                                COMMAND                  CREATED             STATUS              PORTS                                                                                                            NAMES
00101fcf2b57        edgexfoundry/docker-edgex-ui-go:1.0.0                "./edgex-ui-server"      10 seconds ago      Up 8 seconds        0.0.0.0:4000->4000/tcp                                                                                           edgex-ui-go
0e32d55b869b        edgexfoundry/docker-device-virtual-go:1.0.0          "/device-virtual --p…"   10 seconds ago      Up 8 seconds        0.0.0.0:49990->49990/tcp                                                                                         edgex-device-virtual
df98c0f623e5        edgexfoundry/docker-support-rulesengine:1.0.0        "/bin/sh -c 'java -j…"   11 seconds ago      Up 9 seconds        0.0.0.0:48075->48075/tcp                                                                                         edgex-support-rulesengine
90bac9b8c65d        edgexfoundry/docker-export-distro-go:1.0.1           "/export-distro --re…"   11 seconds ago      Up 9 seconds        0.0.0.0:5566->5566/tcp, 0.0.0.0:48070->48070/tcp                                                                 edgex-export-distro
749caa5992b1        edgexfoundry/docker-export-client-go:1.0.1           "/export-client --re…"   12 seconds ago      Up 10 seconds       0.0.0.0:48071->48071/tcp                                                                                         edgex-export-client
11e15cceee84        edgexfoundry/docker-core-command-go:1.0.1            "/core-command --reg…"   13 seconds ago      Up 10 seconds       0.0.0.0:48082->48082/tcp                                                                                         edgex-core-command
7043b6fc3538        edgexfoundry/docker-sys-mgmt-agent-go:1.0.1          "/sys-mgmt-agent --r…"   14 seconds ago      Up 12 seconds       0.0.0.0:48090->48090/tcp                                                                                         edgex-sys-mgmt-agent
6d28367b9f69        edgexfoundry/docker-core-metadata-go:1.0.1           "/core-metadata --re…"   14 seconds ago      Up 13 seconds       0.0.0.0:48081->48081/tcp, 48082/tcp                                                                              edgex-core-metadata
9c874af21d1c        edgexfoundry/docker-core-data-go:1.0.1               "/core-data --regist…"   14 seconds ago      Up 12 seconds       0.0.0.0:5563->5563/tcp, 0.0.0.0:48080->48080/tcp                                                                 edgex-core-data
dcae2e2ca8c1        edgexfoundry/docker-support-notifications-go:1.0.1   "/support-notificati…"   14 seconds ago      Up 12 seconds       0.0.0.0:48060->48060/tcp                                                                                         edgex-support-notifications
d898d9a6e099        edgexfoundry/docker-support-logging-go:1.0.1         "/support-logging --…"   15 seconds ago      Up 14 seconds       0.0.0.0:48061->48061/tcp                                                                                         edgex-support-logging
d754d2c01655        edgexfoundry/docker-edgex-mongo:1.0.1                "docker-entrypoint.s…"   18 seconds ago      Up 16 seconds       0.0.0.0:27017->27017/tcp                                                                                         edgex-mongo
0792d899c127        portainer/portainer                                  "/portainer -H unix:…"   18 seconds ago      Up 16 seconds       0.0.0.0:9000->9000/tcp                                                                                           compose-files_portainer_1
b49d3e57e3c8        consul:1.3.1                                         "docker-entrypoint.s…"   18 seconds ago      Up 16 seconds       0.0.0.0:8400->8400/tcp, 8301-8302/udp, 0.0.0.0:8500->8500/tcp, 8300-8302/tcp, 8600/udp, 0.0.0.0:8600->8600/tcp   edgex-core-consul
2bc99eb0fa72        edgexfoundry/docker-edgex-volume:1.0.0               "/bin/sh -c '/usr/bi…"   19 seconds ago      Up 17 seconds                                                                                                                        edgex-files
```

`GET http://localhost:48081/api/v1/deviceprofile/name/id459543-lora-device_service_profile2` works correctly. You can see the IDs are different than my screenshot above, so this is a subsequent test.

<img width="825" alt="Screen Shot 2019-08-21 at 4 48 06 PM" src="https://user-images.githubusercontent.com/1342980/63470934-81b4d980-c433-11e9-93ef-4bd718208621.png">

`DELETE http://localhost:48081/api/v1/deviceprofile/name/id459543-lora-device_service_profile2` also works as expected. Cannot duplicate this issue.

<img width="1063" alt="Screen Shot 2019-08-21 at 4 49 08 PM" src="https://user-images.githubusercontent.com/1342980/63470987-a90ba680-c433-11e9-8ec9-bd9cdcad7ae0.png">

**Comment by OdysLam** [comment]
I think that this is very interesting, because it seems as an engine problem and not platform dependent. I use postman for my tests.

When attempting to do a generic GET to receive all device profiles:
![image](https://user-images.githubusercontent.com/13405632/63489506-fd0d9e00-c4ba-11e9-8378-26a611685c05.png)

When attempting to POST the profile:
![image](https://user-images.githubusercontent.com/13405632/63489551-1adb0300-c4bb-11e9-87a0-fa229c1dfb5d.png)

When attempting to delete:
![image](https://user-images.githubusercontent.com/13405632/63489577-29c1b580-c4bb-11e9-8bd4-61f4e951e67a.png)

My docker-compose:

```
version: '2.1'
volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  lora-app-server: # lora server
  postgresqldata:
  lora-redis-data:
  node-red-data:
  # portainer_data:

services:
  volume:
    image: edgexfoundry/docker-edgex-volume-arm64:1.0.0
    volumes:
      - db-data:/data
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      
  edgex-core-consul:
    image: consul:1.3.1
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    volumes:
      # - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume  

  edgex-core-config-seed:
    image: edgexfoundry/docker-core-config-seed-go-arm64:1.0.0
    command: ["--profile=docker", "--cmd=/edgex/cmd-redis"]
    volumes:
      # - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - edgex-core-consul 

  edgex-redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - db-data:/data
    depends_on:
      - volume
      
  # edgex-redis:
  #   image: redis:5.0.5-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - db-data:/data
  #   depends_on:
  #     - volume

  edgex-support-logging:
    image: edgexfoundry/docker-support-logging-go-arm64:1.0.1
    ports:
      - "48061:48061"
    volumes:
      # - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - edgex-core-config-seed
      - volume

  # edgex-support-notifications:
  #   image: edgexfoundry/docker-support-notifications-go-arm64:1.0.1
  #   ports:
  #     - "48060:48060" 
  #   volumes:
  #     # - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - edgex-support-logging
  #     - edgex-redis

  edgex-core-metadata:
    image: edgexfoundry/docker-core-metadata-go-arm64:1.0.1
    ports:
      - "48081:48081"
    volumes:
      # - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - edgex-support-logging
      - edgex-redis

  edgex-core-data:
    image: edgexfoundry/docker-core-data-go-arm64:1.0.1
    ports:
      - "48080:48080"
      - "5563:5563"
    volumes:
      # - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - edgex-core-metadata

  edgex-core-command:
    image: edgexfoundry/docker-core-command-go-arm64:1.0.1
    ports:
      - "48082:48082"

    volumes:
      # - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    # depends_on:
    #   - edgex-support-notifications

  edgex-export-client:
    image: edgexfoundry/docker-export-client-go-arm64:1.0.1
    ports:
      - "48071:48071"
    volumes:
      # - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - edgex-core-data
    # environment:
    #   - EXPORT_CLIENT_MONGO_URL=edgex-mongo
    #   - EXPORT_CLIENT_DISTRO_HOST=export-distro
    #   - EXPORT_CLIENT_CONSUL_HOST=edgex-config-seed
  edgex-export-distro:
    image: edgexfoundry/docker-export-distro-go-arm64:1.0.1
    ports:
      - "48070:48070"
      - "5566:5566"
    volumes:
      # - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - edgex-export-client
    environment:
      - EXPORT_DISTRO_CLIENT_HOST=export-client
      - EXPORT_DISTRO_DATA_HOST=edgex-core-data
      - EXPORT_DISTRO_CONSUL_HOST=edgex-config-seed
      - EXPORT_DISTRO_MQTTS_CERT_FILE=none
      - EXPORT_DISTRO_MQTTS_KEY_FILE=none


###### LORA SERVER ####################
  lora-appserver:
    build: ./lora_appserver
    ports:
      - 8080:8080
      - 8001:8001
    # depends_on:
    #   - lora-redis
    #   - lora-postgresql

  # lora-redis:
  #   image: redis:4-alpine
  #   volumes: 
  #     - lora-redis-data:/data
      
  # lora-postgresql:
  #   build: ./postgresql
  #   volumes:
  #     - postgresqldata:/var/lib/postgresql/data
  #   ports: 
  #     - 5432:5432
  #   depends_on:
  #     - volume
  #     - edgex-core-data
  #     - edgex-core-metadata

  #     - edgex-core-consul

###### NODE-RED ####################

  nodered-device-service:
    build: ./nodered
    ports:
        - 1880:1880
    volumes:
    - node-red-data:/data
    depends_on:
      - lora-appserver
      - edgex-core-command
      - edgex-core-metadata
      - edgex-core-data
      - edgex-core-consul
    labels:
      io.balena.features.dbus: '1'
#################################################################
# Device Services
#################################################################

  # edgex-device-virtual:
  #   image: edgexfoundry/docker-device-virtual-arm64:0.5.0

  #   ports:
  #     - "49990:49990"
  #   volumes:
  #     # - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - edgex-core-data
  #     - edgex-core-command

  # device-virtual:
  #   image: edgexfoundry/docker-device-virtual-go-arm64:1.0.0
  #   ports:
  #     - "49990:49990"
  #   volumes:
  #    - db-data:/data/db
  #    - log-data:/edgex/logs
  #    - consul-config:/consul/config
  #    - consul-data:/consul/data
  #   depends_on:
  #     - edgex-core-data
  #     - edgex-core-command
...
```
