### ISSUE TITLE
Vault token not generated for App Services shared DB credentials

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#2530]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Vault Worker
 
It is missing configuration to create token for App Services shared DB credentials

### Is this a regression? 

Yes, in Fuji we have a shared vault token which worked

### Description and Minimal Reproduction

Add the following app service to secure mongo compose file:

```
  app-service-export:
    image: nexus3.edgexfoundry.org:10004/docker-app-service-configurable:master
    ports:
      - "48101:48101"
    container_name: edgex-app-service-configurable-export
    hostname: edgex-app-service-configurable-export
    entrypoint: ["/app-service-configurable"]
    command: ["--registry","--confdir=/res", "--skipVersionCheck=true"]
    networks:
      edgex-network:
        aliases:
          - edgex-app-service-configurable-export
    environment:
      <<: *common-variables
      edgex_profile: http-export
      Service_Host: edgex-app-service-configurable-export
      Service_Port: 48101
      MessageBus_SubscribeHost_Host: edgex-core-data
      Binding_PublishTopic: events
      Writable_StoreAndForward_Enabled: "true"
      Writable_StoreAndForward_RetryInterval: 5s
      Writable_Pipeline_Functions_HTTPPostJSON_Parameters_persistOnError: "true"
      Database_Type: mongodb
      Database_Host: edgex-mongo
      Database_Port: 27017
      SecretStore_TokenFile: /tmp/edgex/secrets/edgex-application-service/secrets-token.json
      SecretStore_Path: /v1/secret/edgex/appservice/
    volumes:
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-application-service:/tmp/edgex/secrets/edgex-application-service:ro,z
    depends_on:
      - consul
      - data
```
## 🔥 Exception or Error
Run the compose and view the log file for this new app service and you will find the following errors:

```
"unable to create shared secret client : HTTP response with status code 403, message: failed to lookup token"
"unable to initialize secret provider"
"SDK initialization failed: boostrapping failed\n"
```

## 🌍  Your Environment
**Deployment Environment:**
Linix

**EdgeX Version:**
Geneva WIP

**Anything else relevant?**

**Comment by bnevis-i** [comment]
Edits:

```
  app-service-export:
    image: nexus3.edgexfoundry.org:10004/docker-app-service-configurable:master
    ports:
      - "48101:48101"
    container_name: edgex-app-service-configurable-export
    hostname: edgex-app-service-configurable-export
    networks:
      edgex-network:
        aliases:
          - edgex-app-service-configurable-export
    environment:
      <<: *common-variables
      edgex_profile: http-export
      Service_Host: edgex-app-service-configurable-export
      Service_Port: 48101
      MessageBus_SubscribeHost_Host: edgex-core-data
      Binding_PublishTopic: events
      Writable_StoreAndForward_Enabled: "true"
      Writable_StoreAndForward_RetryInterval: 5s
      Writable_Pipeline_Functions_HTTPPostJSON_Parameters_persistOnError: "true"
      Database_Host: edgex-redis
      SecretStore_TokenFile: /tmp/edgex/secrets/edgex-application-service/secrets-token.json
      SecretStore_Path: /v1/secret/edgex/appservice/
    volumes:
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-core-metadata:/tmp/edgex/secrets/edgex-application-service:ro,z
    depends_on:
      - consul
      - data
```
