### ISSUE TITLE
[v2 metadata] upload deviceprofile should return 400 when device command's ReadWrite permission doesn't align the deivce resource

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#3264]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
core-metadata

### Description and Minimal Reproduction
The device profile yaml file contains the deviceResource `DeviceValue_String_R` with `R` and the deviceCommand `MotorKind` with `W`:

```
apiVersion: "v2"
name: "Test-Profile-2"
description: "Modbus Honeywell variable speed motors"
manufacturer: "Honeywell"
model: "ABC123"
labels:
  - "modbus"
  - "variable speed motor"
  - "Honeywell"
  - "string_r"
  - "float32_r"

deviceResources:
  - name: "DeviceValue_String_R"
    description: "Generate device string value"
    isHidden: true
    tag: "kind"
    properties:
      valueType: "String"
      readWrite: "R"
  - name: "DeviceValue_FLOAT32_R"
    description: "Generate device FLOAT32 value"
    isHidden: true
    tag: "speed"
    properties:
      valueType: "Float32"
      readWrite: "R"
      floatEncoding: "Base64"
      scale: "0.001"
      units: "kHz"

deviceCommands:
  - name: "MotorKind"
    isHidden: false
    readWrite: W
    resourceOperations:
      - deviceResource: "DeviceValue_String_R"
  - name: "CurrentSpeed"
    isHidden: false
    readWrite: R
    resourceOperations:
      - deviceResource: "DeviceValue_FLOAT32_R"
```

## 🔥 Exception or Error
It should fail to upload the device profile and return 400, but:
```
curl -ki -X POST -F 'file=@./Test-Profile-2.yaml' http://localhost:48081/api/v2/deviceprofile/uploadfile
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
Content-Type: application/json
X-Correlation-Id: 1f79a3d4-a04e-4f47-966b-9b0df76e4cd6
Date: Tue, 16 Mar 2021 04:26:03 GMT
Content-Length: 109

{"apiVersion":"v2","requestId":"","message":"","statusCode":201,"id":"e2c10519-408e-4197-97d4-a29cc5c308fc"}
```

## 🌍  Your Environment

**EdgeX Version:**
master
