### ISSUE TITLE
consul config lost, and some service register failed.

### ISSUE THREAD

**Issue by Haoyuli1990** [edgexfoundry/edgex-go#3585]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
edgex-support-scheduler 
edgex-support-notifications

### Description and Minimal Reproduction

After OS reboot, docker-compose up -d, view consul UI, find some config lost,
and some service register failed, but manual run docker start service can work good.

## 🔥 Exception or Error
<pre><code>

level=ERROR ts=2021-06-21T06:40:18.754566259Z app=edgex-support-notifications source=logger.go:74 msg="logTarget cannot be blank, using stdout only"
level=INFO ts=2021-06-21T06:40:18.754589018Z app=edgex-support-notifications source=registry.go:79 msg="Using Registry (consul) from http://edgex-core-consul:8500"
level=ERROR ts=2021-06-21T06:40:18.754606415Z app=edgex-support-notifications source=bootstrap.go:43 msg="unable to register with Registry in allotted time"
level=INFO ts=2021-06-21T06:47:18.607572886Z app=edgex-support-notifications source=config.go:219 msg="Loaded configuration from /res/configuration.toml"
level=INFO ts=2021-06-21T06:47:18.608740611Z app=edgex-support-notifications source=environment.go:331 msg="Environment override of 'Logging.EnableRemote' by environment variable: Logging_EnableRemote=false"
level=INFO ts=2021-06-21T06:47:18.608811496Z app=edgex-support-notifications source=environment.go:331 msg="Environment override of 'Databases.Primary.Host' by environment variable: Databases_Primary_Host=edgex-redis"
level=INFO ts=2021-06-21T06:47:18.608853108Z app=edgex-support-notifications source=environment.go:331 msg="Environment override of 'Registry.Host' by environment variable: Registry_Host=edgex-core-consul"
level=INFO ts=2021-06-21T06:47:18.608888514Z app=edgex-support-notifications source=environment.go:331 msg="Environment override of 'Service.Host' by environment variable: Service_Host=edgex-support-notifications"
level=INFO ts=2021-06-21T06:47:18.609075775Z app=edgex-support-notifications source=config.go:167 msg="Using Configuration provider (consul) from: http://edgex-core-consul:8500 with base path of edgex/core/1.0/edgex-support-notifications"
level=ERROR ts=2021-06-21T06:47:19.037099004Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2021-06-21T06:47:20.038367505Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2021-06-21T06:47:21.039747869Z app

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
docker-compose file:

```
version: '3.4'

x-common-env-variables: &common-variables
  EDGEX_SECURITY_SECRET_STORE: "false"
  Registry_Host: edgex-core-consul
  Clients_CoreData_Host: edgex-core-data
  Clients_Data_Host: edgex-core-data # For device Services
  Clients_Notifications_Host: edgex-support-notifications
  Clients_Metadata_Host: edgex-core-metadata
  Clients_Command_Host: edgex-core-command
  Clients_Scheduler_Host: edgex-support-scheduler
  Clients_RulesEngine_Host: edgex-kuiper
  Databases_Primary_Host: edgex-redis
  Logging_EnableRemote: "false"

volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:

services:
  consul:
    image: edgexfoundry/docker-edgex-consul:1.2.0
    ports:
      - "0.0.0.0:8400:8400"
      - "0.0.0.0:8500:8500"
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    networks:
      - edgex-network
    volumes:
      - consul-config:/consul/config:z
      - consul-data:/consul/data:z
    environment: 
      - EDGEX_DB=redis
      - EDGEX_SECURE=false

  redis:
    image: redis:5.0.8-alpine
    ports:
      - "0.0.0.0:6379:6379"
    container_name: edgex-redis
    hostname: edgex-redis
    networks:
      - edgex-network
    environment:
      <<: *common-variables
    volumes:
      - db-data:/data:z
  system:
    image: edgexfoundry/docker-sys-mgmt-agent-go:1.2.1
    ports:
      - "0.0.0.0:48090:48090"
    container_name: edgex-sys-mgmt-agent
    hostname: edgex-sys-mgmt-agent
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-sys-mgmt-agent
      ExecutorPath: /sys-mgmt-executor
      MetricsMechanism: executor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
    depends_on:
      - consul
      - scheduler
      - notifications
      - metadata
      - data
      - command

  notifications:
    image: edgexfoundry/docker-support-notifications-go:1.2.1
    ports:
      - "0.0.0.0:48060:48060"
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-support-notifications
    depends_on:
      - consul
      - redis

  metadata:
    image: edgexfoundry/docker-core-metadata-go:1.2.1
    ports:
      - "0.0.0.0:48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-core-metadata
      Service_Timeout: "20000"
      Notifications_Sender: edgex-core-metadata
    depends_on:
      - consul
      - redis
      - notifications

  data:
    image: edgexfoundry/docker-core-data-go:1.2.1
    ports:
      - "0.0.0.0:48080:48080"
      - "0.0.0.0:5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-core-data
    depends_on:
      - consul
      - redis
      - metadata

  command:
    image: edgexfoundry/docker-core-command-go:1.2.1
    ports:
      - "0.0.0.0:48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-core-command
    depends_on:
      - consul
      - redis
      - metadata

  scheduler:
    image: edgexfoundry/docker-support-scheduler-go:1.2.1
    ports:
      - "0.0.0.0:48085:48085"
    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-support-scheduler
      IntervalActions_ScrubPushed_Host: edgex-core-data
      IntervalActions_ScrubAged_Host: edgex-core-data
    depends_on:
      - consul
      - redis

  app-service-rules:
    image: edgexfoundry/docker-app-service-configurable:1.2.0
    ports:
      - "0.0.0.0:48100:48100"
    container_name: edgex-app-service-configurable-rules
    hostname: edgex-app-service-configurable-rules
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      edgex_profile: rules-engine
      Service_Host: edgex-app-service-configurable-rules
      Service_Port: 48100
      MessageBus_SubscribeHost_Host: edgex-core-data
      Binding_PublishTopic: events
    depends_on:
      - consul
      - data

  rulesengine:
    image: emqx/kuiper:0.4.2-alpine
    ports:
      - "0.0.0.0:48075:48075"
      - "0.0.0.0:20498:20498"
    container_name: edgex-kuiper
    hostname: edgex-kuiper
    networks:
      - edgex-network
    environment:
      KUIPER_CONSOLE_LOG: "true"
      KUIPER_REST_PORT: 48075
      EDGEX_SERVER: edgex-app-service-configurable-rules
      EDGEX_SERVICE_SERVER: http://edgex-core-data:48080
      EDGEX_TOPIC: events
      EDGEX_PROTOCOL: tcp
      EDGEX_PORT: 5566
    depends_on:
      - app-service-rules
  device-virtual:
    image: edgexfoundry/docker-device-virtual-go:1.2.2
    ports:
    - "0.0.0.0:49990:49990"
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-device-virtual
    depends_on:
      - consul
      - data
      - metadata
  device-mqtt-owon:
    image: 19900119/hydsoft:new
    ports:
     - "0.0.0.0:49982:49982"
    container_name: edgex-device-mqtt-owon
    hostname: edgex-device-mqtt-owon
    networks:
     - edgex-network
    environment:
     <<: *common-variables
     Service_Host: edgex-device-mqtt-owon
    depends_on:
     - data
     - command
  device-mqtt-android:
    image: 19900119/suntopandroid:new
    ports:
     - "0.0.0.0:49983:49983"
    container_name: edgex-device-mqtt-android
    hostname: edgex-device-mqtt-android
    networks:
     - edgex-network
    environment:
     <<: *common-variables
     Service_Host: edgex-device-mqtt-android
    depends_on:
     - data
     - command
  device-modbus:
    image: edgexfoundry/docker-device-modbus-go:1.2.1
    ports:
     - "0.0.0.0:49991:49991"
    container_name: edgex-device-modbus
    hostname: edgex-device-modbus
    networks:
     - edgex-network
    environment:
     <<: *common-variables
     Service_Host: edgex-device-modbus
    depends_on:
     - data
     - command
  device-metric:
    image: 19900119/edgex-metric-go:new
    ports:
     - "0.0.0.0:49992:49992"
    container_name: edgex-device-metric
    hostname: edgex-device-metric
    networks:
     - edgex-network
    environment:
     <<: *common-variables
     Service_Host: edgex-device-metric
    depends_on:
     - data
     - command
  ui:
    image: edgexfoundry/docker-edgex-ui-go:1.2.1
    ports:
      - "0.0.0.0:4000:4000"
    container_name: edgex-ui-go
    hostname: edgex-ui-go
    networks:
      - edgex-network
  emqx:
    container_name: emqx
    hostname: emqx
    image: emqx/emqx:latest
    ports:
    - 0.0.0.0:18083:18083/tcp
    - 0.0.0.0:1883:1883/tcp
    depends_on:
     - device-mqtt-owon
     - device-mqtt-android
    networks:
      - edgex-network
  edgex-mqtt-engine:
    container_name: edgex-mqtt-engine
    hostname: edgex-mqtt-engine
    networks:
      - edgex-network
    image: 19900119/edgex-mqtt-engine:new
    ports:
    - 0.0.0.0:8086:8086/tcp
networks:
  edgex-network:
    driver: "bridge"
```

**EdgeX Version:**
geneva

**Anything else relevant?**
Run on ubuntu 16.04
