### ISSUE TITLE
Device Profile with Yaml format Can't be marshal  to Json in some case

### ISSUE THREAD

**Issue by wangshihui** [edgexfoundry/edgex-go#3682]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
Metadata

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Maybe No

## 🔥 Exception or Error
<pre><code>

level=ERROR ts=2021-08-25T03:23:50.5747918Z app=core-metadata source=http.go:47 X-Correlation-ID=14a42ea6-c394-41c3-8bcd-a29b9f5e6835 msg="unable to JSON marshal device profile for Redis persistence -> json: unsupported type: map[interface {}]interface {}"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Window10 for development
Ubuntu 18.04.4 LTS for deployment

**EdgeX Version:**
2.0 ireland

**Anything else relevant?**
when  add some complex vaules to  the attributes of deviceResources in the device profile. error happens. 
eg:
```
...
...
deviceResources:
- description: on/off
  name: Motion
  isHidden: false
  tag: ""
  properties:
    valueType: String
    readWrite: R
    units: ""
    minimum: ""
    maximum: ""
    defaultValue: "off"
    mask: ""
    shift: ""
    scale: ""
    offset: ""
    base: ""
    assertion: ""
    mediaType: ""
  attributes:
   ext: [{"action":{ "get": ""},"group":"xxx","id":"xxx","alias":"xxxx"}]
...
...
```
the vaule of `attributes ` can not be a cmplext objet. it can only be made string  or numberic.

this isuue cased by the yaml pkg of golang `gopkg.in/yaml.v2`. see https://github.com/go-yaml/yaml/issues/137

And I test the `gopkg.in/yaml.v3` is ok. what about change the yml pkg ver  to v3. https://github.com/go-yaml/yaml/tree/v3

All the V3 api is  backwards compatibility

Also the device service sdk has the same issue when load the device profile.
