### ISSUE TITLE
How to send a notification email by SMTP

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/edgex-go#3992]
Hi all :
I can get the notification when the device was deleted, but now I can not get the notification mail.
I have been set up the configuration of notification service.

My version is Jakarta.

---
docker-compose 
```
notifications:
    container_name: edgex-support-notifications
    depends_on:
    - consul
    - database
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-support-notifications
    hostname: edgex-support-notifications
    image: edgexfoundry/support-notifications-arm64:2.1.0
    volumes:
    - /etc/EdgeX/res/notification:/res
    networks:
      edgex-network: {}
    ports:
    - 59860:59860
    read_only: true
    security_opt:
    - no-new-privileges:true
    user: root:root
    restart: always
```

configuration.toml
```
[Writable]
LogLevel = "INFO"
ResendLimit = 2
ResendInterval = "5s"
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
    path = "redisdb"
      [Writable.InsecureSecrets.DB.Secrets]
      username = ""
      password = ""
    [Writable.InsecureSecrets.SMTP]
    path = "smtp"
      [Writable.InsecureSecrets.SMTP.Secrets]
      username = "bighb69738@gmail.com"
      password = "App Passwords"

[Service]
HealthCheckInterval = "10s"
Host = "localhost"
Port = 59860
ServerBindAddr = "" # Leave blank so default to Host value unless different value is needed.
StartupMsg = "This is the Support Notifications Microservice"
MaxResultCount = 1024
MaxRequestSize = 0 # Not curently used. Defines the maximum size of http request body in bytes
RequestTimeout = "5s"
  [Service.CORSConfiguration]
  EnableCORS = false
  CORSAllowCredentials = false
  CORSAllowedOrigin = "https://localhost"
  CORSAllowedMethods = "GET, POST, PUT, PATCH, DELETE"
  CORSAllowedHeaders = "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID"
  CORSExposeHeaders = "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
  CORSMaxAge = 3600

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[Databases]
  [Databases.Primary]
  Host = "localhost"
  Name = "notifications"
  Port = 6379
  Timeout = 5000
  Type = "redisdb"

[Smtp]
  Host = "smtp.gmail.com"
  Port = 587
  Sender = "bighb69738@gmail.com"
  EnableSelfSignedCert = false
  Subject = "EdgeX Notification"
  # SecretPath is used to specify the secret path to store the credential(username and password) for connecting the SMTP server
  # User need to store the credential via the /secret API before sending the email notification
  SecretPath = "smtp"
  # AuthMode is the SMTP authentication mechanism. Currently, "usernamepassword" is the only AuthMode supported by this service, and the secret keys are "username" and "password".
  AuthMode = "usernamepassword"


[SecretStore]
Type = "vault"
Protocol = "http"
Host = "localhost"
Port = 8200
Path = "support-notifications/"
TokenFile = "/tmp/edgex/secrets/support-notifications/secrets-token.json"
RootCaCertPath = ""
ServerName = ""
SecretsFile = ""
DisableScrubSecretsFile = false
  [SecretStore.Authentication]
  AuthType = "X-Vault-Token"
  [SecretStore.RuntimeTokenProvider]
  Enabled = false
  Protocol = "https"
  Host = "localhost"
  Port = 59841
  TrustDomain = "edgexfoundry.org"
  EndpointSocket = "/tmp/edgex/secrets/spiffe/public/api.sock"
  RequiredSecrets = "redisdb"
```

Subscription
<img width="1135" alt="截圖 2022-04-27 上午8 05 46" src="https://user-images.githubusercontent.com/38970513/165412585-ff05b61c-dcad-4181-8b36-4b4d08a3d64f.png">

Notification
<img width="1173" alt="截圖 2022-04-27 上午8 06 33" src="https://user-images.githubusercontent.com/38970513/165412669-a3fa4214-6042-4500-9665-ff52645f9195.png">
