### ISSUE TITLE
Pull access denied for edgexfoundry/docker-device-uart, repository does not exist

### ISSUE THREAD

**Issue by vediyappan-villali** [edgexfoundry/edgex-go#4003]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
edgexfoundry-holding/device-uart/

### Is this a regression?

N/A

### Description and Minimal Reproduction [**REQUIRED**]

1. Add the device-uart  to the docker-compose.yml 

```
  device-uart:
    container_name: edgex-device-uart
    depends_on:
    - consul
    - data
    - metadata
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-device-uart
    hostname: edgex-device-uart
    image: edgexfoundry/device-uart:0.0.0-dev
    networks:
      edgex-network: {}
    ports:
    - 49995:49995/tcp
    read_only: false
    privileged: true
    volumes:
    - "/dev:/dev"
    security_opt:
    - no-new-privileges:false
    user: root:root
```
2. Run "docker-compose pull". The below error will be seen.

vediyappan@vediyappan-desktop:~/work/edgex-experiments/geneva$ docker-compose pull

[+] Running 12/13
 ⠿ device-random Pulled3.1s
 ⠿ device-uart Error                                                                                                                                                                                  ....
**Error response from daemon: pull access denied for edgexfoundry/docker-device-uart, repository does not exist or may require 'docker login': denied: requested access to the resource is denied**

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
2.1-Jakarta

**Anything else relevant?**

![image](https://user-images.githubusercontent.com/75830844/166435322-4966d0ed-7236-4e7c-93cd-189e9cd5d456.png)
file:///home/vediyappan/work/edgex-experiments/geneva/docker-compose.yml
