### ISSUE TITLE
Can not use REST API to access the EdgeX service with docker swarm.

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/edgex-go#4115]
Hi all,
I tried to deploy EdgeX service with docker swarm.
Now I can not access any EdgeX service by REST API, but i can access the edgex-ui service by http://localhost:4000.
And the edgex-ui can show the events from the device service.

### docker-compose
```
networks:
  edgex-network:
    driver: overlay
    attachable: true
services:
  app-service-rules:
    depends_on:
    - consul
    - data
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_PROFILE: rules-engine
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-app-rules-engine
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-redis
    hostname: edgex-app-rules-engine
    image: edgexfoundry/app-service-configurable-arm64:2.0.1
    networks:
      edgex-network: {}
    ports:
      - target: 59701
        published: 59701
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id == nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: 2002:2001
  command:
    depends_on:
    - consul
    - database
    - metadata
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-core-command
    hostname: edgex-core-command
    image: edgexfoundry/core-command-arm64:2.0.0
    networks:
      edgex-network: {}
    ports:
      - target: 59882
        published: 59882
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id == nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: 2002:2001
  consul:
    hostname: edgex-core-consul
    image: consul:1.9.5
    networks:
      edgex-network: {}
    ports:
      - target: 8500
        published: 8500
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id == nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: root:root
    volumes:
    - consul-config:/consul/config:z
    - consul-data:/consul/data:z
  data:
    depends_on:
    - consul
    - database
    - metadata
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-core-data
    hostname: edgex-core-data
    image: edgexfoundry/core-data-arm64:2.0.0
    networks:
      edgex-network: {}
    ports:
      - target: 5563
        published: 5563
        mode: host
      - target: 59880
        published: 59880
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id == nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: root:root
  database:
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      ADD_SECRETSTORE_TOKENS: "device-simple"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
    hostname: edgex-redis
    image: redis:6.2.4-alpine
    networks:
      edgex-network: {}
    ports:
      - target: 6379
        published: 6379
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id == nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: root:root
    volumes:
    - db-data:/data:z
  metadata:
    depends_on:
    - consul
    - database
    - notifications
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      NOTIFICATIONS_SENDER: edgex-core-metadata
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-core-metadata
    hostname: edgex-core-metadata
    image: edgexfoundry/core-metadata-arm64:2.0.0
    networks:
      edgex-network: {}
    ports:
      - target: 59881
        published: 59881
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id == nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: 2002:2001
  notifications:
    depends_on:
    - consul
    - database
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-support-notifications
    hostname: edgex-support-notifications
    image: edgexfoundry/support-notifications-arm64:2.0.0
    networks:
      edgex-network: {}
    ports:
      - target: 59860
        published: 59860
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id == nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: 2002:2001
  rulesengine:
    depends_on:
    - database
    environment:
      EDGEX__DEFAULT__PORT: 6379
      EDGEX__DEFAULT__PROTOCOL: redis
      EDGEX__DEFAULT__SERVER: edgex-redis
      EDGEX__DEFAULT__TOPIC: rules-events
      EDGEX__DEFAULT__TYPE: redis
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__RESTPORT: 59720
    hostname: edgex-kuiper
    image: lfedge/ekuiper:1.3.0-alpine
    networks:
      edgex-network: {}
    ports:
      - target: 59720
        published: 59720
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id == nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: kuiper:kuiper
    volumes:
    - kuiper-data:/kuiper/data:z
  scheduler:
    depends_on:
    - consul
    - database
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      INTERVALACTIONS_SCRUBAGED_HOST: edgex-core-data
      INTERVALACTIONS_SCRUBPUSHED_HOST: edgex-core-data
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-support-scheduler
    hostname: edgex-support-scheduler
    image: edgexfoundry/support-scheduler-arm64:2.0.0
    networks:
      edgex-network: {}
    ports:
      - target: 59861
        published: 59862
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id == nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: 2002:2001
  ui:
    image: edgexfoundry/edgex-ui-arm64:2.0.0
    networks:
      edgex-network: {}
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id == nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: 2002:2001
  device-mqtt:
    container_name: edgex-device-mqtt
    depends_on:
      - consul
      - data
      - metadata
      - mqtt-broker
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      MQTTBROKERINFO_HOST: edgex-mqtt-broker
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-device-mqtt
      DEVICE_DEVICESDIR: /custom-config/devices
      DEVICE_PROFILESDIR: /custom-config/profiles
    hostname: edgex-device-mqtt
    image: edgexfoundry/device-mqtt:0.0.0-test
    volumes:
    - ./custom-config:/custom-config
    - ./res/mqtt-device:/res
    networks:
      edgex-network: {}
    ports:
      - target: 59982
        published: 59982
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id != nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: 2002:2001
  mqtt-broker:
    command: /usr/sbin/mosquitto -c /mosquitto-no-auth.conf
    container_name: edgex-mqtt-broker
    hostname: edgex-mqtt-broker
    image: eclipse-mosquitto:2.0.11
    networks:
      edgex-network: {}
    ports:
      - published: 1883
        target: 1883
        mode: host
    deploy:
      placement:
        constraints: 
          - node.id == nvk9x9vh9dhd3ws3zechsh006
    read_only: true
    user: 2002:2001
version: '3.7'
volumes:
  consul-config: {}
  consul-data: {}
  db-data: {}
  kuiper-data: {}

```

### docker version
```
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 19:02:03 2020
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 19:00:21 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
### docker ps
<img width="1439" alt="截圖 2022-08-02 下午12 32 52" src="https://user-images.githubusercontent.com/38970513/182292284-4b98c1a1-7302-4fe2-828d-ff760c910eed.png">

### The log of core-data
<img width="1440" alt="截圖 2022-08-02 下午2 04 20" src="https://user-images.githubusercontent.com/38970513/182303394-129590d6-c736-4dc1-a0ba-8239c9b064f9.png">

### Consul
<img width="1395" alt="截圖 2022-08-02 下午12 33 41" src="https://user-images.githubusercontent.com/38970513/182292823-9f47903d-a1b7-4920-987d-be159c5af8f7.png">

### The error respond of GET http request 

http request
```
curl -X 'GET' \
'http://localhost:59880/api/v2/ping' \
-H 'accept: application/json'
```
Respond
```
curl: (56) Recv failure: Connection reset by peer
```
