### ISSUE TITLE
Remove extra hyphen out of the core-metadata.yaml

### ISSUE THREAD

**Issue by judehung** [edgexfoundry/edgex-go#4377]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: openapi/v3/core-metadata.yaml

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
Three `map[string]any` fields are recently added into DTOs:
1. tags field of Device DTO
2. properties field of Device DTO
3. properties field of ProvisionWatcher
The proper way to show `map[string]any` in swagger is like following:
```
tags:
  tag1:
    field1: "field1Value"
    field2: "field2Value"
  tag2:
    field3: "field3Value"
    field4: "field4Value"
    field5: "field5Value"
```
However, https://github.com/edgexfoundry/edgex-go/pull/4375 accidentally add extra hyphens like following:
```
tags:
  - tag1:
      field1: "field1Value"
      field2: "field2Value"
  - tag2:
      field3: "field3Value"
      field4: "field4Value"
      field5: "field5Value"
```
Those hyphens should be removed for proper map[string] representation.

## 🔥 Exception or Error
N/A

## 🌍  Your Environment
**Deployment Environment:**
N/A
**EdgeX Version [**REQUIRED**]:**
3.0.0

**Anything else relevant?**
No
