### ISSUE TITLE
How to write request body with PUT command for Interval action 

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/edgex-go#4500]
Scheduler version 2.1.0

device profile:
```
name: "sensor1"
manufacturer: "TEST"
model: "1"
labels:
 - "test"
description: "Sensor"
deviceResources:
  -
    name: "Record"
    description: "Record"
    attributes:
      { type: "Record" }
    properties:
      valueType: "int64"
      readWrite: "RW"
```

I try to use REST API to add interval action, and it is my request body:
`
[
    {
        "apiVersion": "v2",
        "action": {
            "name": "TEST",
            "intervalName": "1min",
            "address": {
                "type": "REST",
                "host": "edgex-core-command",
                "port": 59882,
                "path": "/api/v2/device/name/sensor1/Record",
                "httpMethod": "PUT",
                "RequestBody": {"Record": "11"}
            },
            "adminState": "UNLOCKED"
        }
    }
]
`

But It doesn't work, and the error message from schedule service:
`
app=support-scheduler source=manager.go:139 msg="fail to send request with RESTAddress, err: request failed, status code: 500, err: {\"apiVersion\":\"v2\",\"message\":\"failed to parse request body\",\"statusCode\":500}\n"
`

the error message from core-command service:
`
app=core-command source=http.go:38 X-Correlation-ID=af610e71-64fe-460c-a210-dc14e7173e6a msg="failed to parse request body -> unexpected end of JSON input"
`

How to fix this error?
