### ISSUE TITLE
Core Data Retention and Persistent Caps implementation

### ISSUE THREAD

**Issue by jumpingliu** [edgexfoundry/edgex-go#4618]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for Core Data

### Description [**REQUIRED**]
Approved UCR: https://docs.edgexfoundry.org/3.0/design/ucr/Core-Data-Retention/

**Comment by weichou1229** [comment]
@jpwhitemn @lenny-intel  According to the UCR and [ADR](https://github.com/edgexfoundry/edgex-docs/pull/723/files), we consider do the following implementation, could you please help review?

Add the configurations to toml file,
```
Retention:
  Enabled: false
  Interval: 30s          # purging interval defines when the database should be rid of readings above the high watermark.
  MaxCap: 10000    #  The maximum capacity defines where the high watermark of readings should be detected for purging the amount of the reading to the minimum capacity.
  MinCap: 8000     # The minimum capacity defines where the total count of readings should be returned to during purging. 
```
If the Retention.Enabled set to `true`, 
1. Core data will create a schedule to trigger the reading purging 
2. When the reading amount reaches the MaxCap, Core data should purge the amount of the reading to the minimum capacity. 
   For example, 
    - If MaxCap is 10000 and MinCap is 8000, and the amount of readings is greater than 10000, the core data 
  should purge the amount of the reading to 8000.
    - the core data will use the 8001st reading to find the related event's origin time, and reusing the [DeleteEventsByAge function](https://github.com/edgexfoundry/edgex-go/blob/541cc85a126a37ebcd17b753a9f4f7f76549fffd/internal/pkg/infrastructure/redis/event.go#L103) to purge readings. (If we only remove readings and related events, some readings might lose the related event)
