### ISSUE TITLE
invalid query parameter, yes has to be true or false

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/edgex-go#4728]
I tried to use device-template by edgex-core-command service with device-sdk-c v3.0.0.

After the command is executed by edgex-ui, the following error message appears:

level=ERROR ts=2023-11-27T02:04:45.784550087Z app=core-command source=http.go:47 X-Correlation-ID=a9b7866d-cb5b-432a-afa0-fadc0f6addf1 msg="invalid query parameter, yes has to be true or false"
level=ERROR ts=2023-11-27T02:04:59.671497315Z app=core-command source=http.go:47 X-Correlation-ID=4c8a5db4-be40-4432-b39e-267caefbbdfb msg="invalid query parameter, yes has to be true or false"

How to fix it?

docker-compose file
```
services:
  app-rules-engine:
    container_name: edgex-app-rules-engine
    depends_on:
      consul:
        condition: service_started
      core-data:
        condition: service_started
    environment:
      EDGEX_PROFILE: rules-engine
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-app-rules-engine
    hostname: edgex-app-rules-engine
    image: edgexfoundry/app-service-configurable-arm64:3.0.0
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 59701
      published: 59701
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  consul:
    command:
    - agent
    - -ui
    - -bootstrap
    - -server
    - -client
    - 0.0.0.0
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    image: hashicorp/consul:1.15.2
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 8500
      published: 8500
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: root:root
    volumes:
    - type: volume
      source: consul-config
      target: /consul/config
      volume: {}
    - type: volume
      source: consul-data
      target: /consul/data
      volume: {}
  core-command:
    container_name: edgex-core-command
    depends_on:
      consul:
        condition: service_started
      core-metadata:
        condition: service_started
      database:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      EXTERNALMQTT_URL: tcp://edgex-mqtt-broker:1883
      SERVICE_HOST: edgex-core-command
    hostname: edgex-core-command
    image: edgexfoundry/core-command-arm64:3.0.0
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 0.0.0.0
      target: 59882
      published: 59882
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  core-common-config-bootstrapper:
    container_name: edgex-core-common-config-bootstrapper
    depends_on:
      consul:
        condition: service_started
    environment:
      ALL_SERVICES_DATABASE_HOST: edgex-redis
      ALL_SERVICES_MESSAGEBUS_HOST: edgex-redis
      ALL_SERVICES_REGISTRY_HOST: edgex-core-consul
      APP_SERVICES_CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      DEVICE_SERVICES_CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      EDGEX_SECURITY_SECRET_STORE: "false"
    hostname: edgex-core-common-config-bootstrapper
    image: edgexfoundry/core-common-config-bootstrapper-arm64:3.0.0
    networks:
      edgex-network: null
    read_only: true
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  core-data:
    container_name: edgex-core-data
    depends_on:
      consul:
        condition: service_started
      core-metadata:
        condition: service_started
      database:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-core-data
    hostname: edgex-core-data
    image: edgexfoundry/core-data-arm64:3.0.0
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 59880
      published: 59880
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  core-metadata:
    container_name: edgex-core-metadata
    depends_on:
      consul:
        condition: service_started
      database:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-core-metadata
    hostname: edgex-core-metadata
    image: edgexfoundry/core-metadata-arm64:3.0.0
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 0.0.0.0
      target: 59881
      published: 59881
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  database:
    container_name: edgex-redis
    hostname: edgex-redis
    image: redis:7.0.11-alpine
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 6379
      published: 6379
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: root:root
    volumes:
    - type: volume
      source: db-data
      target: /data
      volume: {}
  device-example:
    container_name: edgex-device-example
    depends_on:
      consul:
        condition: service_started
      core-data:
        condition: service_started
      core-metadata:
        condition: service_started
    environment:
      SERVICE_HOST: edgex-device-example
      EDGEX_SECURITY_SECRET_STORE: "false"
    hostname: edgex-device-example
    image: edgex-csdk-example:3.0.0
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 0.0.0.0
      target: 59990
      published: 59990
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    privileged: true
    user: root:root
  rules-engine:
    container_name: edgex-kuiper
    depends_on:
      database:
        condition: service_started
    environment:
      CONNECTION__EDGEX__REDISMSGBUS__PORT: "6379"
      CONNECTION__EDGEX__REDISMSGBUS__PROTOCOL: redis
      CONNECTION__EDGEX__REDISMSGBUS__SERVER: edgex-redis
      CONNECTION__EDGEX__REDISMSGBUS__TYPE: redis
      EDGEX__DEFAULT__PORT: "6379"
      EDGEX__DEFAULT__PROTOCOL: redis
      EDGEX__DEFAULT__SERVER: edgex-redis
      EDGEX__DEFAULT__TOPIC: edgex/rules-events
      EDGEX__DEFAULT__TYPE: redis
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__RESTPORT: "59720"
    hostname: edgex-kuiper
    image: lfedge/ekuiper:1.9.2-alpine
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 59720
      published: 59720
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: kuiper:kuiper
    volumes:
    - type: volume
      source: kuiper-data
      target: /kuiper/data
      volume: {}
    - type: volume
      source: kuiper-etc
      target: /kuiper/etc
      volume: {}
    - type: volume
      source: kuiper-log
      target: /kuiper/log
      volume: {}
    - type: volume
      source: kuiper-plugins
      target: /kuiper/plugins
      volume: {}
  support-notifications:
    container_name: edgex-support-notifications
    depends_on:
      consul:
        condition: service_started
      database:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-support-notifications
    hostname: edgex-support-notifications
    image: edgexfoundry/support-notifications-arm64:3.0.0
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 59860
      published: 59860
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  support-scheduler:
    container_name: edgex-support-scheduler
    depends_on:
      consul:
        condition: service_started
      database:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      INTERVALACTIONS_SCRUBAGED_HOST: edgex-core-data
      INTERVALACTIONS_SCRUBPUSHED_HOST: edgex-core-data
      SERVICE_HOST: edgex-support-scheduler
    hostname: edgex-support-scheduler
    image: edgexfoundry/support-scheduler-arm64:3.0.0
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 59861
      published: 59861
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  ui:
    container_name: edgex-ui-go
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-ui-go
    hostname: edgex-ui-go
    image: edgexfoundry/edgex-ui-arm64:3.0.0
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      target: 4000
      published: 4000
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
networks:
  edgex-network:
    name: edgex_edgex-network
    driver: bridge
volumes:
  consul-config:
    name: edgex_consul-config
  consul-data:
    name: edgex_consul-data
  db-data:
    name: edgex_db-data
  kuiper-data:
    name: edgex_kuiper-data
  kuiper-etc:
    name: edgex_kuiper-etc
  kuiper-log:
    name: edgex_kuiper-log
  kuiper-plugins:
    name: edgex_kuiper-plugins
```

device:
```
{
  "name": "Device1",
  "profileName": "TemplateSensor",
  "description": "An Example Template Device",
  "protocols":
  {
     "Other": { "Address": "someSensorEndpoint" }
  }
}
```

profile:
```
{
  "name": "TemplateSensor",
  "manufacturer": "IoTechSystems",
  "model": "IoT0",
  "description": "Template Sensor",
  "labels": ["sensor"],
  "apiVersion": "v2",

  "deviceResources":
  [
    {
      "name": "SensorOne",
      "description": "A Sensor generating unsigned integer values",
      "attributes": { "SensorID": "Sen1" , "SensorType": "UInt64" },
      "properties": { "valueType": "Uint64", "readWrite": "R", "units": "things" }
    },
    {
      "name": "SensorTwo",
      "description": "A Sensor generating unsigned integer values",
      "attributes": { "SensorID": "Sen2", "SensorType": "UInt64" },
      "properties": { "valueType": "Uint64", "readWrite": "R", "units": "things" }
    },
    {
      "name": "Switch",
      "description": "A generic switch",
      "attributes": { "SensorID": "Switch1", "SensorType": "Switch" },
      "properties": { "valueType": "Bool", "readWrite": "RW", "units": "State" }
    }
  ]
}
```
