### ISSUE TITLE
Fix the permission denied error in postgres_wait_install script in security bootstrapper

### ISSUE THREAD

**Issue by lindseysimple** [edgexfoundry/edgex-go#4901]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in `postgres_wait_install` entrypoint script in security bootstrapper while running Postgres service with Security mode is enabled.

### Is this a regression?

 No.

### Description and Minimal Reproduction [**REQUIRED**]
Add the following edgex-postgres to [docker-compose.yml](https://github.com/edgexfoundry/edgex-compose/blob/main/docker-compose.yml) to start Postgres service with Security and start the EdgeX services with `docker compose up -d` command:
```
edgex-postgres:
    container_name: edgex-postgres
    depends_on:
      security-bootstrapper:
        condition: service_started
        required: true
      security-secretstore-setup:
        condition: service_started
        required: true
    entrypoint:
      - /edgex-init/postgres_wait_install.sh
    environment:
      DATABASECONFIG_NAME: create-users.sh
      DATABASECONFIG_PATH: /tmp/postgres-init-scripts
      EDGEX_SECURITY_SECRET_STORE: "true"
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      SECRETSTORE_HOST: edgex-vault
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-postgres
      STAGEGATE_DATABASE_PORT: "5432"
      STAGEGATE_DATABASE_READYPORT: "5432"
      STAGEGATE_PROXYSETUP_READYPORT: "54325"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-keeper
      STAGEGATE_REGISTRY_PORT: "59890"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edgex_db
    hostname: postgres
    image: postgres:16.3-alpine3.20
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 5432
        published: "5432"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run
      - /tmp
    user: root:root
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume: { }
      - type: volume
        source: edgex-init
        target: /edgex-init
        read_only: true
        volume: { }
      - type: bind
        source: /tmp/edgex/secrets/security-bootstrapper-postgres
        target: /tmp/edgex/secrets/security-bootstrapper-postgres
        read_only: true
        bind:
          selinux: z
          create_host_path: true
```

## 🔥 Exception or Error
Got the following error in the `edgex-postgres` service log:
<pre><code>
level=INFO ts=2024-09-04T08:52:41.87796327Z app=security-bootstrapper-postgres source=secret.go:216 msg="load token from file"
level=WARN ts=2024-09-04T08:52:41.877982603Z app=security-bootstrapper-postgres source=secret.go:132 msg="Retryable failure while creating SecretClientt: open /tmp/edgex/secrets/security-bootstrapper-postgres/secrets-token.json: permission denied"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 20

**EdgeX Version [**REQUIRED**]:** 3.2
