### ISSUE TITLE
Update configuration with environment override not works in Common Config

### ISSUE THREAD

**Issue by lindseysimple** [edgexfoundry/edgex-go#5086]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

The issue is located in **core-common-config-bootstrapper** service.

### Is this a regression?

No.

### Description and Minimal Reproduction [**REQUIRED**]

The common configuration has not been overwritten by setting the `EDGEX_OVERWRITE_CONFIG` environment variable in the docker compose file. For example:

```
 core-common-config-bootstrapper:
    environment:
      EDGEX_OVERWRITE_CONFIG: "true"
      DEVICE_SERVICES_DEVICE_MAXCMDOPS: 5
```

The common configuration should be overwritten same as the result by adding the `-o` flag.

## 🌍  Your Environment

**EdgeX Version [**REQUIRED**]:**

EdgeX v4, and also in v3.
