### ISSUE TITLE
Add system management agent to snap

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#624]
For Delhi, there will be an additional service, the Micro Service Management. We need to add this into the snap.

See also issue #581

**Comment by anonymouse64** [comment]
@akramtexas I'm having some difficulty starting up the system management agent from the snap and am hoping you can help me diagnose the issue here. When I run the system management agent from the snap , it panics:

```
+ /snap/edgexfoundry/x1/bin/sys-mgmt-agent --consul
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x658e63]

goroutine 33 [running]:
github.com/edgexfoundry/edgex-go/vendor/github.com/hashicorp/consul/api.(*Client).newRequest(0x0, 0x7aadfc, 0x3, 0x7aef68, 0x12, 0x0)
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/vendor/github.com/hashicorp/consul/api/api.go:644 +0x63
github.com/edgexfoundry/edgex-go/vendor/github.com/hashicorp/consul/api.(*Agent).Services(0xc42004cd80, 0x0, 0x0, 0x0)
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/vendor/github.com/hashicorp/consul/api/agent.go:245 +0x6d
github.com/edgexfoundry/edgex-go/internal/pkg/consul.GetServiceEndpoint(0x7b04cd, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/internal/pkg/consul/client.go:108 +0x76
github.com/edgexfoundry/edgex-go/internal/pkg/startup.Endpoint.Monitor(0x7b04cd, 0x15, 0x7aac25, 0x1, 0x1, 0xc42031a5e0, 0x16, 0x3a98, 0xc420270ae0)
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/internal/pkg/startup/endpoint.go:29 +0x1c8
created by github.com/edgexfoundry/edgex-go/pkg/clients/general.(*generalRestClient).init
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/pkg/clients/general/client.go:42 +0xd5
```

We are running it like this:
```bash
cd $SNAP_DATA/config/sys-mgmt-agent
$SNAP/bin/sys-mgmt-agent --consul &
```
and the configuration file is located in `$SNAP_DATA/config/sys-mgmt-agent/res/configuration.toml` and looks like this:

```toml
ApplicationName = 'edgex-sys-mgmt-agent'
ConsulProfilesActive = 'go'
ValidateCheck = false
AppOpenMsg = 'This is the System Management Agent Service'
FormatSpecifier = '%(\\d+\\$)?([-#+ 0(\\<]*)?(\\d+)?(\\.\\d+)?([tT])?([a-zA-Z%])'
ServicePort = 48090
ServiceTimeout = 5000
ServiceAddress = 'localhost'
CheckInterval = '10s'
EnableRemoteLogging = false
LoggingFile = '/var/snap/edgexfoundry/common/sys-mgmt-agent.log'

[Clients]
  [Clients.Notifications]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48060

  [Clients.Command]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48082

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Scheduler]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48085

  [Clients.Export]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48071

  [Clients.Distro]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48070
```
