### ISSUE TITLE
config-seed panics when support-scheduler config directory is missing

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#715]
Sometime over the past weekish (git bisect hasn't finished running), config-seed stopping working insofar as it panics:

```
INFO: 2018/10/22 13:21:41 Service dependencies resolved...
INFO: 2018/10/22 13:21:41 dir: device-virtual file: application.properties
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x67d378]

goroutine 1 [running]:
github.com/edgexfoundry/edgex-go/vendor/github.com/pelletier/go-toml.(*Tree).ToMap(0x0, 0x49)
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/vendor/github.com/pelletier/go-toml/tomltree_write.go:318 +0x48
github.com/edgexfoundry/edgex-go/internal/seed/config.ImportConfiguration(0x7ffd541502af, 0x20, 0x0, 0x0, 0x0, 0x0)
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/internal/seed/config/populate.go:103 +0x81c
main.main()
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/cmd/config-seed/main.go:53 +0x384
```

config-seed is being invoked as follows:
```
cd "$SNAP_DATA"/config/config-seed

"$SNAP"/bin/config-seed -c "$SNAP_DATA"/config
```

I have confirmed that consul is running before running config-seed here and this is the filesystem layout (`$SNAP_DATA` is `/var/snap/edgexfoundry/x1`):
```
$ tree /var/snap/edgexfoundry/x1/config
/var/snap/edgexfoundry/x1/config
├── config-seed
│   └── res
│       ├── configuration.toml
│       └── properties
│           └── device-virtual
│               └── application.properties
├── core-command
│   └── res
│       └── configuration.toml
├── core-data
│   └── res
│       └── configuration.toml
├── core-metadata
│   └── res
│       └── configuration.toml
├── export-client
│   └── res
│       └── configuration.toml
├── export-distro
│   └── res
│       └── configuration.toml
├── security-api-gateway
│   ├── kong.conf
│   └── res
│       └── configuration.toml
├── security-secret-store
│   ├── pki-setup-config-kong.env
│   ├── pki-setup-config-vault.env
│   └── vault-config.json
├── support-logging
│   └── res
│       └── configuration.toml
└── support-notifications
    └── res
        └── configuration.toml
```

And this is what `$SNAP_DATA/config/config-seed/res/configuration.toml` looks like:
```toml
ConfigPath = './config'
GlobalPrefix = 'config'
ConsulProtocol = 'http'
ConsulHost = 'localhost'
ConsulPort = 8500
IsReset = true
FailLimit = 30
FailWaitTime = 3
AcceptablePropertyExtensions = ['.toml','.yaml', '.yml', '.properties']
YamlExtensions = ['.yaml','.yml']
TomlExtensions = ['.toml']
EnableRemoteLogging = false
LoggingFile = '/var/snap/edgexfoundry/common/config-seed.log'
LoggingRemoteURL = ''
```

**Comment by anonymouse64** [comment]
git bisect says that commit d94a43b6a84cc70db43741cbf9889f761873a511 is the first bad commit with config-seed panic'ing... 

Ping @xmlviking 

I tested this by running:
```bash
$ git bisect start
$ git bisect good ae3fe6bca783f4918524acdc99d80d68bcdd5255 # <- just randomly picked a commit and manually tested it to see that config-seed works
$ git bisect bad a2a4db692884540bc9cac525de7fd63fb2636f51 # <- this is current master, which panics
$ git bisect run $(pwd)/test-config-seed-snap.sh
```

where `test-config-seed-snap.sh` is:
```bash
#!/bin/bash -e

# remove old snaps
rm -rf *.snap
# build the snap
set +e
if ! snapcraft ; then
	snapcraft clean
	snapcraft
fi
set -e
# remove old snap
sudo snap remove edgexfoundry
# install the snap
sudo snap install --devmode edgexfoundry*.snap
# turn everything off so just consul + config-seed runs
echo "SECURITY=n" | sudo tee --append /var/snap/edgexfoundry/current/edgex-services-env
echo "CORE_METADATA=n" | sudo tee --append /var/snap/edgexfoundry/current/edgex-services-env
echo "CORE_DATA=n" | sudo tee --append /var/snap/edgexfoundry/current/edgex-services-env
echo "CORE_COMMAND=n" | sudo tee --append /var/snap/edgexfoundry/current/edgex-services-env
echo "DEVICE_VIRTUAL=n" | sudo tee --append /var/snap/edgexfoundry/current/edgex-services-env
# remove the old log file
rm edgex.log
# start edgexfoundry - putting stderr to the log file
sudo edgexfoundry.start-edgex 2>edgex.log
# check the log
if grep "panic: runtime error:" edgex.log ; then
	exit 1
else
	exit 0
fi
```

Which basically just builds the snap from that commit, turns off all the services except config-seed (which always runs), then checks the output from config-seed for "panic: runtime error:".

**Comment by tsconn23** [comment]
@anonymouse64 I suspect the problem here, based on the SHA you referenced, is that the support-scheduler directory is missing from `/var/snap/edgexfoundry/x1/config`. The PR containing that commit was to add the support-scheduler service and as such, the populate.go file is looping through a list of expected directories. Based on the directory dump you provided, when it tries to access the non-existent directory, the service panics. 

See if that fixes the issue.

**Comment by anonymouse64** [comment]
@tsconn23 thanks for the input, I'll try adding the directory and see how it does

**Comment by anonymouse64** [comment]
@tsconn23 So I tried adding the support-scheduler configuration files to that directory and now it doesn't panic, it just mysteriously dies:
```
INFO: 2018/10/30 18:21:19 Service dependencies resolved...
INFO: 2018/10/30 18:21:19 dir: device-virtual file: application.properties
```

The directory layout:
```
$ tree /var/snap/edgexfoundry/x1/config
/var/snap/edgexfoundry/x1/config
├── config-seed
│   └── res
│       ├── configuration.toml
│       └── properties
│           └── device-virtual
│               └── application.properties
├── core-command
│   └── res
│       └── configuration.toml
├── core-data
│   └── res
│       └── configuration.toml
├── core-metadata
│   └── res
│       └── configuration.toml
├── export-client
│   └── res
│       └── configuration.toml
├── export-distro
│   └── res
│       └── configuration.toml
├── security-api-gateway
│   ├── kong.conf
│   └── res
│       └── configuration.toml
├── security-secret-store
│   ├── pki-setup-config-kong.env
│   ├── pki-setup-config-vault.env
│   └── vault-config.json
├── support-logging
│   └── res
│       └── configuration.toml
├── support-notifications
│   └── res
│       └── configuration.toml
└── support-scheduler
    └── res
        └── configuration.toml

23 directories, 15 files
```

Contents of `configuration.toml` for support-scheduler:

```toml
ScheduleInterval = 500

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48085
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is the Support Scheduler Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = '/var/snap/edgexfoundry/common/support-scheduler.log'

[Clients]
  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Schedules]
    [Schedules.Midnight]
    Name = 'midnight'
    Start = '20180101T000000'
    Frequency = 'P1D'

[ScheduleEvents]
    [ScheduleEvents.ScrubPushed]
    Name = 'scrub-pushed-events'
    Host = 'localhost'
    Port = 48080
    Protocol = 'http'
    Method = 'DELETE'
    Service = 'core-data'
    Path = '/api/v1/event/scrub'
    Schedule = 'midnight'
    Scheduler = 'support-scheduler'

    [ScheduleEvents.ScrubAged]
    Name = 'scrub-aged-events'
    Host = 'localhost'
    Port = 48080
    Protocol = 'http'
    Method = 'DELETE'
    Service = 'core-data'
    Path = '/api/v1/event/removeold/age/604800000'
    Schedule = 'midnight'
    Scheduler = 'support-scheduler'






```

Only other things changed are that the snap doesn't contain the java version of `support-scheduler` and instead has the go version.
