### ISSUE TITLE
Specify epochs for the snap to prevent automatic delhi->edinburgh refresh

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#799]
Currently all setup is done once, during the `install` hook which installs everything into $SNAP_DATA, however this is problematic on refreshing ~~because the $SNAP_DATA dir is cleaned out~~ (see below https://github.com/edgexfoundry/edgex-go/issues/799#issuecomment-476341118 ) so it can be restored on a revert, so the post-refresh hook needs to set everything up again like the install hook.

EDIT: see later comments

**Comment by anonymouse64** [comment]
Another way we could avoid this is to use $SNAP_COMMON, but that would require ensuring that we don't break compatibility of how we layout $SNAP_COMMON in between releases and is probably not a good guarantee right now

**Comment by anonymouse64** [comment]
A word so I don't forget as I hit this with another snap:
* `$SNAP_DATA` is actually copied over from a previous revision to the new revision on a refresh
* However, the configuration files as processed/configured will still point at the previous revision as the file paths will be absolute and environment variables such as $SNAP, $SNAP_DATA, etc. all point to the actual revision number and not to the `current` symlink

One way we could avoid this is to manually build up the paths such that the paths for $SNAP and $SNAP_DATA actually are using the `current` symlink. 

Another way would be to strip the revision number out of $SNAP and $SNAP_DATA as they appear in the snap environment we run inside, and then add `current` at the end as the revision number. This could be done with a simple sed:

```bash
$ echo $SNAP_DATA
/var/snap/edgexfoundry/x1
$ echo $SNAP_DATA | sed s@$SNAP_REVISION\$@current@
/var/snap/edgexfoundry/current
```

The last way we could do this is in the post-refresh hook just re-process all the configuration files like we do in the install hook, as proposed in this original issue, but that seems heavy-handed and could overwrite user changes to the files that were done after initial installation but before refresh.

**Comment by anonymouse64** [comment]
Based on guidance from https://forum.snapcraft.io/t/guidance-on-usage-of-current-in-snap-data-et-al/10589/2 I think the right way we want do handle this is:

* change the install hook to use `current` everywhere instead of the verbatim revision number we have now from `$SNAP_DATA`, etc.
* Add a `pre-refresh` hook that sets a config item (a la `snapctl set lastrev=$SNAP_REVISION`) saving the previous revision before a refresh
* Add a post-refresh hook that checks for the config item `lastrev`, and if found, then don't update any config items, however if it is found then do checks to see if the relevant settings in the config files match `$SNAP_DATA` stripped of the last element + some number. If it matches that pattern, then update those to use `current`.

There are 2 cases we need to start handling in the code:
* When the snap is refreshed from a version with explicit revision number
* When the snap is installed fresh with a new revision using `current` in the install hook

The new `install` hook using `current` will handle the first case, while the second case will be handled the first refresh by the new revision's `post-refresh` hook, and the new `pre-refresh` hook from that new revision will ensure future refreshes from that point on don't modify the config items as they will either have been set manually by the user and thus deviate from the pattern mentioned above, or they will have been updated to use `current` and won't need to be updated for future refreshes.

**Comment by anonymouse64** [comment]
Another facet about this that needs to be handled is how to automatically migrate config files from the old format to a new one, as for example with Delhi we have this configuration.toml:
```toml
ConfigPath = './config'
GlobalPrefix = 'config'
ConsulProtocol = 'http'
ConsulHost = 'localhost'
ConsulPort = 8500
IsReset = true
FailLimit = 30
FailWaitTime = 3
AcceptablePropertyExtensions = ['.toml','.yaml', '.yml', '.properties']
YamlExtensions = ['.yaml','.yml']
TomlExtensions = ['.toml']
EnableRemoteLogging = false
LoggingFile = '/var/snap/edgexfoundry/common/config-seed.log'
LoggingRemoteURL = ''
LoggingLevel = 'INFO'
```

while now with master/edinburgh we have this configuration.toml:

```toml
ConfigPath = './config'
GlobalPrefix = 'config'
IsReset = true
FailLimit = 30
FailWaitTime = 3
AcceptablePropertyExtensions = ['.toml','.yaml', '.yml', '.properties']
YamlExtensions = ['.yaml','.yml']
TomlExtensions = ['.toml']
EnableRemoteLogging = false
LoggingFile = './logs/edgex-config-seed.log'
LoggingRemoteURL = 'http://localhost:48061/api/v1/logs'
LoggingLevel = 'INFO'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'
```

While crude, it might be easiest to automatically process these changes by transforming the toml file as it is during the post-refresh hook into JSON, applying the update changes to the JSON and then re-transforming it back into toml. A bit of a hack but that would give us maximal upgrade compatibility
